clawpack/riemann_book

Euler_approximate_solvers.ipynb, Euler_equations.ipynb, exact_solvers/Euler.py, exact_solvers/__init__.py
See the notebooks here: 
- http://nbviewer.ipython.org/gist/ketch/445f886de2d09c763f1b
- http://nbviewer.ipython.org/gist/ketch/0a7397cbd3f1d937d1be
This PR combines some existing materials from other places into a first draft of a chapter on the Euler equations.  It covers (in outline, at least) the equations, the exact Riemann solution, and two approximate solvers (HLLE and Roe).  The discussion of the mathematical structure of the equations and of the approximate solvers has not been filled in yet.  This is mostly copied from other notebooks written previously by @rjleveque and myself.
Questions for @rjleveque and @maojrs:
- Does this outline look like the right set of things we want to cover?
- What do you think about the vertical layout of plots?  This requires my branch of Riemann …
=> [WIP] First draft of Euler chapter

Euler_approximate_solvers.ipynb, Euler_equations.ipynb
Use interact instead of StaticInteract.
Use FloatSlider instead of RangeWidget.
Use Latex labels for sliders.
=> Update Euler notebooks to use current ipywidgets.

utils/riemann_tools.py
In some solvers (such as f-wave Riemann solvers for problems with
spatially-varying flux, as well as many multi-dimensional solvers), there is a
wave with speed zero that is not explicitly calculated or returned from the
solver since it is not needed in the numerical update.  This commit
modifies riemann_tools.riemann_solution() to accept a keyword argument
stationary_wave.  If this argument is set to True, then the states
are calculated inward from both left and right, and a stationary wave
is inferred from the difference between the neighboring states.
If stationary_waves==False, the routine checks is the computed
right state (from summing the waves) is close to the input
right state.  If not, it suggests setting stationary_wave=True.
This commit also adds a fwave option, which divides …
=> Extend riemann_solution() to infer stationary waves.

Nonlinear_elasticity.ipynb
Also remove space from nonlinear elasticity notebook filename.
This resolves the issues that @rjleveque was seeing.  There was a bug involving the difference between a space and an underscore.
=> Correctly set stress relation.

Traffic_flow.ipynb, Traffic_variable_speed.ipynb, exact_solvers/traffic_variable_speed.py
Also add citation in basic traffic notebook.
=> Add variable speed traffic notebook.

utils/animation_tools.py
Needed for a notebook I'm working on...
=> return anim from make_anim_from_plotdir

Traffic_variable_speed.ipynb, exact_solvers/traffic_variable_speed.py, utils/riemann_tools.py
Discuss the choice of which density to jump to at interface.
Add widget with sliders for left/right densities and velocities,
including f-q plane plot in output.
=> Better q-f plane plots and explanations for variable LWR chapter.

.travis.yml, Euler_approximate_solvers.ipynb, Euler_equations.ipynb, README.md, Traffic_flow.ipynb, exact_solvers/Euler.py, exact_solvers/__init__.py, exact_solvers/nonlinear_elasticity.py, exact_solvers/traffic_variable_speed.py, requirements.txt, test.py
The test script simply executes each notebook.
=> Add test script, requirements, and travis script.

Traffic_flow.ipynb, Traffic_variable_speed.ipynb, riemann.bib
Also add a reference.
docathon
=> Explain bottleneck when speed limit decreases.

Traffic_variable_speed.ipynb, utils/riemann_tools.py
See the variable-speed traffic notebook for demonstrations (all in widgets).
=> Add capability to plot ordinary characteristics.

Traffic_variable_speed.ipynb, exact_solvers/traffic_variable_speed.py, utils/riemann_tools.py
Also fix some bugs in characteristic plotting and improve
variable speed traffic notebook.
=> More flexible plotting of Riemann solutions.

Traffic_flow.ipynb, Traffic_variable_speed.ipynb, exact_solvers/traffic_LWR.py, utils/riemann_tools.py
Now they're alongside the solution plots throughout the
notebook.  I also moved some of the traffic solver code
down into exact_solvers/.
=> Incorporate car trajectories in traffic notebook.

Advection.ipynb
I suggested yesterday to @rjleveque that maybe we didn't need this, but after thinking about traffic flow and other physical applications I thought that it would be worth introducing this just to get the idea of conservation of mass out of the way (not that we want to spend much time on that in this book), and it wouldn't hurt to have this basic, trivial example of a Riemann problem.  I'm still wondering if we want to place it before or after the acoustics chapter...
=> Initial draft of advection notebook.

Traffic_variable_speed.ipynb
Adds a time slider, characteristics, and f-f(q) plots (all suggested by Lisa Davis).
Eventually this material will go in a separate chapter in the section on approximate solvers.
=> Improve presentation of approximate solvers for vc traffic.

Euler_equations.ipynb, Shallow_water.ipynb, exact_solvers/Euler.py, exact_solvers/shallow_water.py, utils/riemann_tools.py
- Exact solver correctly handles all vacuum states.
- Plotting of characteristics
- Better phase plane plots
- Cleaner code
There are further improvements to be made -- I think we should switch to primitive variables for the solution plots.  But I'll go ahead and merge this since it also resolves #53.
=> Improvements to Euler notebook

Euler_approximate_solvers.ipynb, Euler_equations.ipynb, Euler_equations_TammannEOS.ipynb, Nonlinear_elasticity.ipynb, Shallow_water.ipynb, Traffic_variable_speed.ipynb, exact_solvers/Euler.py, utils/riemann_tools.py
Also adds an easy way to do this for other systems.  Just pass a function that converts from the conserved variables to the primitive (or other) variables, as an argument to plot_riemann or make_plot_function.
Hopefully this does what @maojrs asked for in #54.
=> Plot with primitive variables in Euler notebook.

Kitchen_sink_problem.ipynb, riemann.bib
This chapter investigates the circular hydraulic jump.  It is different from the other chapters since the states away from the jump are smoothly varying rather than constant.
One issue at the moment is that you have to execute the javascript cell to get equation numbering working.  I believe I can fix this soon.
=> Initial draft of kitchen sink chapter.

Euler_approximate_solvers.ipynb, Index.ipynb, Kitchen_sink_problem.ipynb, Pressureless_flow.ipynb, Shallow_water.ipynb, exact_solvers/shallow_water.py, utils/riemann_tools.py
For fun I used the notation of shallow water flow (in zero-gravity) for this.  We can change it all to use isothermal flow instead if desired.
I had never delved into this before but had a lot of fun learning about it with the tools we had developed (and by reading @rjleveque's 2003 paper on the topic).
=> Add notebook on pressureless flow

Preface.ipynb, Traffic_flow.ipynb, html.tpl, make_html.py
This script creates html files from the notebooks but suffers from #80.
I also fixed a typo and a merge issue I noticed.
I suggest we merge this and then work on improving the html rendering of equation numbers later.
=> make_html.py script added

Acoustics.ipynb, Euler_equations.ipynb, Euler_equations_TammannEOS.ipynb, Index.ipynb, Kitchen_sink_problem.ipynb, Nonconvex_Scalar_Osher_Solution.ipynb, Nonlinear_elasticity.ipynb, Pressureless_flow.ipynb, Traffic_flow.ipynb, Traffic_variable_speed.ipynb, riemann.html, riemann_bib.html
Bibtex references using `data-cite=...` have to end with `</a></cite>`, not `<a></cite>`.
These notebooks looked fine as notebooks but rendered wrong as html.
=> fix </a> at end of data-cite bibtex references

Pressureless_flow.ipynb
After this PR, there are still code lines that run into the margin but I believe none run off the page.
=> Shorten some code lines that ran off the page in PDF.

Preface.ipynb, README.md
Also some updating of links to notebooks.  But this needs more cleanup eventually.
=> Update README.md with links to html pages, Azure, Docker.

Pressureless_flow.ipynb
Other questions about this notebook:
- The figures with 4 plots across are very cramped and the titles run together, both in the notebook and in the pdf.  Replace by a 2x2 array of plots?
- I think this is the only notebook with Exercises as such.  Do we want to do this more generally?
=> Minor changes to Pressureless_flow.ipynb

Euler_equations_TammannEOS.ipynb, exact_solvers/euler_tammann.py, utils/riemann_tools.py
I also raised some issues in the form of markdown cells with red text that I added, mostly about the last few examples. I don't think they are explained properly and I'm not sure what exactly was intended regarding discussing shocks passing through an interface.
Also it seems like the left-going shock should be a rarefaction in some cases?
=> Fixed some problems in Euler_equations_TammannEOS.ipynb 

Index.ipynb, Nonconvex_scalar.ipynb, make_pdf.py
Improvements to Nonconvex_scalar notebook (also renamed).
Now uses widgets like other notebooks and converts to JSAnimation in the html version.
Also added convex hull plots and refactored the functions.
Might want to move the plotting functions to a Python module?  As it is, there's a lot to skip over before getting to the figures.  But in this instance I think the reader might be interested in how the various plots are created.
=> Nonconvex scalar

Docker.md, Dockerfile
Docker stacks based Dockerfile was over 6g, making it really large.
This takes quite a long time to build on user's computers. The
newer one is simpler & is only 1g, much faster to build.
Also fixed issue with permissions in home directory, & ipywidgets
not working.
=> Fix permissions + make docker image much smaller

Approximate_solvers.ipynb, Euler_approximate_solvers.ipynb, Index.ipynb, Preface.ipynb, README.md, riemann.bib
- new notebook `Approximate_solvers.ipynb`
- some updates to other introductory material
- pointers to beta.mybinder version
=> Approximate solver intro notebook

Shallow_water.ipynb, exact_solvers/shallow_water.py, make_html_on_master.py, make_pdf.py
I cleaned up Shallow_water to show less code in the pdf version and modified some text so it reads better without this code in place.
I also fixed the plotting for the case of non-physical rarefactions so that the interact's can all be replaced by `jsanimate_widgets.interact` in the html version.
I pushed a new html version of this notebook to http://www.clawpack.org/riemann_book/html/Shallow_water.html
=> Shallow water cleanup

Euler_equations_TammannEOS.ipynb, Introduction.ipynb, Nonconvex_scalar.ipynb, Shallow_water.ipynb, Traffic_flow.ipynb, Traffic_variable_speed.ipynb, make_pdf.py
I hid more code in several of the notebooks and selected a smaller set to put in a pdf file.
=> Clean up for short pdf version

Euler_equations_TammannEOS.ipynb, exact_solvers/nonlinear_elasticity.py, utils/riemann_tools.py
This PR mainly adds documentation to functions in riemann_tools.  After not looking at this code for a few months, I came back and added documentation to the parts that were not immediately clear.
=> Document and clean up riemann_tools.py.

Acoustics.ipynb, Acoustics_heterogeneous.ipynb, Euler_equations.ipynb, Introduction.ipynb, custom.css, exact_solvers/shallow_water.py, make_html_on_master.py, make_pdf.py, riemann.bib, utils/animation_tools.py, utils/snapshot_widgets.py
Add more historical notes at the beginning of the introduction.
Minor editorial changes to the text.
Examples of the Riemann solution as description of large-scale behavior.
Note on the last point: I wanted to add this as further motivation for studying the Riemann problem, after Constantine Dafermos mentioned it during a talk here at KAUST.  I'm not aware of a formal statement or theorem describing the tendency discussed in the notebook; if either of you are, please let me know.
The plots of the "macroscopic behavior" examples don't quite match the other plots, and are rendered as JSanimations currently.  I can fix this if/after we agree that this section belongs in the introduction.
=> Revise introduction.

Introduction.ipynb, custom.css
- Fix custom.css for more consistent margins.
- Revise list of physical applications included in the book.
=> Address RJL comments on Introduction.ipynb.

Acoustics.ipynb, Advection.ipynb, Euler_equations.ipynb, Introduction.ipynb, Shallow_water.ipynb, Traffic_flow.ipynb, exact_solvers/shallow_water.py
I accidentally omitted these from the last PR.
=> Incorporate suggestions from @maojrs.

animation_tools_demo.ipynb, utils/animation_tools.py
Fixes to `make_html` and `make_rst` to properly load html text.
Added `animation_tools_demo.ipynb` for testing everything.
=> Animation tools fix

utils/animation_tools.py, utils/jsanimate_widgets.py
Second attempt and untangling mixed branches.
Also change some figsizes for better resolution animations.
It also helps to set
```
mpl.rcParams['figure.dpi'] = 100
```
in each notebook using this, I think.
=> Revert JSAnimate

Index.ipynb, Nonconvex_scalar.ipynb, exact_solvers/nonconvex.py, exact_solvers/nonconvex_demos.py
Conglomeration of earlier commits moving code out to utils/nonconvex*.py
and adding final example with slider bars for ql and qr
Cleaned up from #144 commits.
=> Updated Nonconvex_scalar.ipynb

Shallow_water.ipynb, exact_solvers/shallow_demos.py, exact_solvers/shallow_water.py
I created `exact_solvers/shallow_demos.py`.
I'm also working on `Shallow_tracer.ipynb` and will add a new version of that to this PR as well.
I also plan to move some of the demo code used in the Introduction from `exact_solvers/shallow_water.py` to `exact_solvers/shallow_demos.py`.
=> WIP: moved code out of Shallow_water.ipynb

Acoustics.ipynb, exact_solvers/acoustics_demos.py
Resolves https://github.com/clawpack/riemann_book/issues/155.  Thanks to @maojrs for catching these errors.
=> Fix some mathematical errors in acoustics notebook.

Index.ipynb
Some parts were numbering from 0 instead of from 1.  This fixes that.
=> Fix chapter numbering in Index.

Euler.ipynb, Euler_approximate.ipynb, Euler_compare.ipynb, exact_solvers/euler_stripes.py, utils/riemann_tools.py
Clean up discussion of linearly degenerate waves to be consistent
with Shallow water tracer chapter.
Fix stripes plot so it works with t=0 and the plot titles don't overlap
other plots.
For some reason the Euler stripes plotting was set up as a standalone thing (rather than using riemann_tools), which is why it didn't just work correctly.
=> Minor improvements to Euler and Euler_compare chapters.

Euler_compare.ipynb
Based on suggestions from @maojrs.  This addresses most of the comments in https://github.com/clawpack/riemann_book/issues/166.
=> Add more explanation in Euler_compare chapter.

Euler.ipynb, Euler_approximate.ipynb, Shallow_water_approximate.ipynb, exact_solvers/Euler.py
This PR moves some code into files and consolidates a lot of duplicated code into functions.  There's still much more code in the approximate solvers notebooks than in the notebooks of Part I, but I think this is okay.
=> Move more code to files

riemann.html
Same as https://github.com/clawpack/doc/pull/202 ;-)
=> Hyperlink DOIs to preferred resolver

Traffic_variable_speed.ipynb
A few corrections pointed out by Lisa Davis.
=> Fix some important typos in the variable speed traffic notebook.

Acoustics.ipynb, Advection.ipynb, Introduction.ipynb, exact_solvers/acoustics_demos.py
Some suggested changes in the first three chapters after the preface.
I just noticed the Preface comes out as Chapter 1 in the pdf, maybe we need to fix this.
=> Some edits to chapters 2,3,4

Acoustics.ipynb, Advection.ipynb, Burgers.ipynb, Euler.ipynb, Introduction.ipynb, Nonconvex_scalar.ipynb, Shallow_tracer.ipynb, Shallow_water.ipynb, Traffic_flow.ipynb, utils/change_ql.py
I used the script `utils/change_ql.py` to change `_l` to `_\ell` in all markdown cells.
=> Change q_l to q_\ell etc.

FV_compare.ipynb, Index.ipynb
So that it fits better in the page head of the pdf file
=> Shorten chapter title

Docker.md, Dockerfile
I tested that this works, also on binder.
=> Update Dockerfile and documentation for Clawpack v5.7.0

README.md
Add more links now that the SIAM book is published, and various minor improvements.
=> Update README.md for SIAM book
