clawpack/riemann_book

utils/__init__.py
utils/animation_tools.py
utils/nbtools.py
utils/riemann_tools.py

So we can work on improving these tools and easily import them in notebooks.
- `riemann_tools.py` came from `clawpack/apps/notebooks`,
- `nbtools.py` came from `clawpack/clawutil/src/python/clawutil`,
- `animation_tools.py` came from latest AMath 574 version in https://github.com/amath574w2017/am574-class
Examples using `animation_tools.py` can be found in `clawpack/apps/notebooks/visclaw/animation_tools_demo.ipynb`

Most recent versions of some tools in a new utils directory

---

utils/riemann_tools.py

This seems to fix #8.
Previously we were using this with StaticInteract, which no longer exists.  Calling it now from `ipywidgets.interact` was generating duplicate plots.  As far as I can tell that was because interact was both creating a figure and returning the figure returned by plot_function.  This changes that behavior so that only one set of plots appears in the notebook.

Don't return anything from plot_function created by make_plot_function.

---

utils/riemann_tools.py

This was problematic when plot_riemann was called repeatedly
with different characteristic velocities, e.g. when comparing
different approximate Riemann solvers.  The old code created
time indicators with slightly different x-offsets, one on top
of the other.

Change plot_riemann to avoid duplicate time indicators.

---

exact_solvers/Euler.py

This code functions the same as the old code; the hold() commands are not necessary with recent versions of matplotlib.

Remove plt.hold() as it is deprecated.

---

exact_solvers/traffic_variable_speed.py

Some degenerate cases (with wave strength zero) were not handled correctly in the exact solver, which could lead to division by zero with just the right initial data.  This avoids that.

Correctly handle rare situations in LWR exact Riemann solver.

---

Euler_equations.ipynb

Should we do this instead?  It avoids having to clear this cell manually before committing changes.

link to file rather than using %load

---

Euler_equations.ipynb
utils/animation_tools.py
utils/riemann_tools.py

This seems to be necessary after recent updates to
matplotlib and/or ipywidgets.
@rjleveque Please check whether this breaks the widgets when combined with your current versions of things.

Add calls to `plt.show()` in various places.

---

Shallow_water.ipynb
exact_solvers/shallow_water.py
utils/riemann_tools.py

So that it plots a gap rather than a discontinuity that doesn't agree with the x-t plane plot in the `Shallow_water.ipynb` notebook.

Modified reval function for shallow water to return nan in overturning case

---

utils/riemann_tools.py

If no variable names are provided, use labels like $q_j$ instead of q[j].  The labels are indexed from 1.
This replaces https://github.com/clawpack/riemann_book/pull/20.

Use latex axis labels for q components.

---

Introduction.ipynb
exact_solvers/shallow_water.py
riemann.tplx

- Resolve issues with t=0 (see #75)
- Make all code fit on page by shortening lines and reducing code font size
- Avoid using top-level header (#) since that gets converted to a new chapter
A PDF showing how things look with these changes is here:
https://www.dropbox.com/s/9huu3ig543ut528/riemann.pdf?dl=0

Improve presentation of Introduction in PDF.

---

Docker.md
Dockerfile

- Easier to launch a Jupyter Notebook
- Works with beta.mybinder.org 
- Uses Jupyter DockerStacks (https://github.com/jupyter/dockerstacks) rather than Anaconda2 directly (this sets up Jupyter properly by default)
- Run as a non-root user by default (this is required to run on beta.mybinder.org, and is also a good security practice)
- Use COPY instead of git clone to copy contents of directory to container image (this lets you test local changes without having to push them, plus is much faster)
- Don't put directories in /, put them in $HOME (also required to make this usable by non-root users)
I can also help set up an automated push to dockerhub, so users can run this locally simply with a 
docker run command, without having to build it themselves. Also it looks like clawpack supports …

Make the repository work with beta.mybinder.org

---

Euler_equations_TammannEOS.ipynb

I suggest we might want to do this in this notebook and perhaps elsewhere so that html version looks nicer than what currently shows up here: http://www.clawpack.org/riemann_book/html/Euler_equations_TammannEOS.html
```
import warnings
warnings.filterwarnings("ignore")
```
I also fixed a citation `</a>` one place.

Turn off warnings in Euler_equations_TammannEOS

---

Acoustics.ipynb
Index.ipynb
Nonlinear_elasticity.ipynb
Traffic_variable_speed.ipynb

Fix some things that break in the html version.
For future reference:
- Make sure to have `</a>` at end of citations,
- Leave blank line before and after displayed equations in markdown
- make sure `from ipywidgets import interact` is on a separate line. Use another line to import other things from `ipywidgets` since this line is replaced when converting to html or pdf.

Fixes for html

---

make_html_on_master.py

Better workflow for making html files, to avoid having to merge all changes to master into gh-pages branch all the time and worrying about changes to `ipynb` files being on the wrong branch:
- Use this new `make_html_on_master.py` script on master
- View files in `build_html` to make sure they look good, adjust notebook and remake if needed.
- Check out gh-pages branch
- Copy all files from `build_html` to `html`
- Commit and push only the changes to `html` directory to Github to show up on web.

Make html on master

---

exact_solvers/traffic_variable_speed.py

Some of the exact Riemann solver code has become quite messy, particularly for problems where there are a number of cases that must be explicitly separated.  The main problem is the definition of the riemann_eval() function, which is done separately for every case.
This PR shows how this can be cleaned up in the case of the variable speed limit LWR solver.  I added a single function that generically creates riemann_eval() for all of the 8 cases.  My goal here was to make the solver as short and readable as possible; I think that now it is as short as it can be while still showing clearly the full Riemann solution.
Later, I'll probably extend this to work for other solvers that have a lot of cases (like the "traffic with an on-ramp" chapter) and move the generic make_reval() function to …

Make a single reval function instead of a separate one for each case, in variable speed limit traffic solver.

---

Traffic_flow.ipynb
exact_solvers/traffic_LWR.py
utils/riemann_tools.py

This PR fixes some situations in which plot x- or y-ranges were set to have the same min and max values (which caused matplotlib to print a warning) in riemann_tools.py.
It also adds a keyword argument xmax to plot_riemann(), allowing the user to specify a range for the x-axis rather than having it scale automatically.  This seems generally better for interacts.
Finally, I added an improved interact widget to the first traffic notebook, at the end.  The x-axis range control is included, and different sliders are put in separate columns.  I left the code for this in the notebook for the moment for easy inspection, though we'll want to move it to a file later.
Thanks to @maojrs for pointing out these issues and for showing me (via his interactive pplanes code) how to lay out better widgets. …

Interact improvements

---

riemann.tplx

This fixes the issue that all the text was stripped out of the PDF when using recent versions of pandoc.

Change command-line option in nbconvert template for compatibility with updated pandoc.

---

Approximate_solvers.ipynb
Burgers_approximate.ipynb
Euler_approximate_solvers.ipynb
Shallow_water_approximate_solvers.ipynb

I'm starting to go through Part II.  A few questions so far...
1. **Approximate_solvers.ipynb**
1. I had to define macros for \wave, \amdq, \apdq for the latex to work
and I did so in a cell above the first cell that appears.
Is this already done somewhere else?
I tagged this cell as "raw", thinking we may need to convert this into
a "raw nbconvert" cell in order to get it to render properly in the pdf?
See https://github.com/jupyter/nbconvert/issues/312.
1. **Burgers_approximate.ipynb**
1. In the transonic rarefaction section, `q_m` is used in several places
that should possibly be `q_s`?
1. Should we move some of the code, e.g. the definition of `setup`, to 
a separate file that is imported?

WIP: making a pass on Part II

---

Traffic_flow.ipynb
exact_solvers/traffic_LWR.py
exact_solvers/traffic_demos.py

For the moment, `traffic_demos.py` is in the `exact_solvers` folder.  I tried putting it in a parallel folder called `demos`, but then it was more difficult to import.  I think we would need to add an `__init__.py` in the base `riemann_book` folder (so that the whole book is a Python package) and then readers would need to add the folder above `riemann_book` to their python path, or we would need to have Python actually install the package to a system folder.  I wasn't sure that we wanted to add that additional installation requirement.  It seems simpler to have the exact solvers and the demos in separate files in the same folder.  Perhaps we could rename the folder to `solvers_and_demos` or something similar.  In any case, I think it's okay to merge this PR and decide later on the …

Move demo code from traffic notebook into traffic_demos.py.

---

Nonconvex_scalar.ipynb

Also I added a comment that the last example doesn't work in the html version:  I think because of multiple sliders not converting to jsAnimation, this only works for a single time-slider.  Maybe we should figure out a way to handle other cases?
Hmm, I take it back.  For some reason the last time I created the new html file it did work, though it didn't previously. See http://www.clawpack.org/riemann_book/html/Nonconvex_scalar.html

fix figsizes in  Nonconvex_scalar by loading matplotlib in separate cell

---

Euler_compare.ipynb

I think this is a useful notebook.
For the Sod problem it is stated that the "fine grid" solution can be viewed as the exact solution, but as computed (especially in the first example where the clawpack solver is used with only 1000 points) the contact discontinuity is quite smeared out, which could lead to confusion on the part of the reader.  I tried changing to sharpclaw with 2000 points and it looks a bit better, maybe go to an even finer grid?  Or hardwire the exact solution since we have it?
I added some comment about the fact that a single Riemann problem is solved numerically to perhaps avoid confusion with the exact Riemann problem.
The initial data used for the blast wave problem seems to be specified as
```
q_l = Euler.conservative_to_primitive(1.,0.,1.)
q_r = …
```

Some suggestions to Euler_compare.ipynb

---

Acoustics.ipynb

Equation (4) wasn't  rendering properly in the html version and I finally figure out it was because one line of the markdown cell started with a + sign, and the line was interpreted as a bullet point even though it was in the middle of a latex align environment.

Cannot start a line with + sign in markdown

---

Shallow_water_approximate.ipynb

When I taught from this chapter, I felt that there ought to be a comparison of full FV solutions using the two Riemann solvers at the end.  This PR adds a PyClaw dam-break simulation with Roe and HLLE.  The basic takeaway is that the two solvers give almost the same solution on any reasonable grid, despite the fact that the underlying approximate Riemann solutions are so different.  I think it is important for students to be aware of this.
I'm open for suggestions of other things to include.

Add pyclaw simulation at end of SW approx notebook.

---

Preface.ipynb
riemann.bib
riemann.html
riemann_bib.html

WIP, updating some discussion in Preface.  I removed link to Azure since I don't want to maintain that along with binder.  I added some more references to other books, but not at all sure this is the optimal short list of other references to give, so feel free to suggest changes/additions.
I added a few more notes on things still to do in #196.

Edits to Preface and additions to .bib

---

Dockerfile

This Dockerfile is much simpler and loads on binder much more quickly since it is based on the docker image for clawpack-v5.6.0 on dockerhub.
I just tested this again on binder and it seems to work fine.  Try it at:
https://mybinder.org/v2/gh/rjleveque/riemann_book/Dockerfile_v5.6.0

Dockerfile that uses clawpack-v5.6.0 from dockerhub

---

Acoustics.ipynb
Advection.ipynb
Burgers.ipynb
Burgers_approximate.ipynb
Euler.ipynb
FV_compare.ipynb
Introduction.ipynb
Nonconvex_scalar.ipynb
Shallow_tracer.ipynb
Shallow_water.ipynb
Traffic_flow.ipynb

Add commas and periods to github links, in a way that the footnotes render properly
in latex with the footnote superscripts after the punctuation.

github punctuation

---

utils/riemann_tools.py

Using float steps in `np.linspace` was deprecated in numpy 1.12 and removed in 1.18 with [this commit](https://github.com/numpy/numpy/commit/f4dfe833e3e037bb69113f7250fad3699f918cfc).
With this change `make_pdf.py` runs and produces the pdf.

fix float index in riemann_tools

---

utils/riemann_tools.py

sympy is only used if verbose==True and I don't think we use this in the notebooks, so I suggest we move the import into this `if verbose` block.

Remove sympy dependency

---

Acoustics.ipynb

The new acoustics figure was being rendered very large in the notebook, so I embedded the picture using Image from Ipython display, like done in the Traffic flow notebook. Sorry for the double pull request.

Resized new acoustics figure

---

Acoustics.ipynb
Acoustics_heterogeneous.ipynb
Advection.ipynb
Burgers.ipynb
Burgers_approximate.ipynb
Euler.ipynb
Euler_approximate.ipynb
FV_compare.ipynb
Index2.ipynb
Introduction.ipynb
Nonconvex_scalar.ipynb
Preface.ipynb
Shallow_tracer.ipynb
Shallow_water.ipynb
Shallow_water_approximate.ipynb
Traffic_flow.ipynb

To agree with changes in the SIAM book version. We will maintain branch FA16 in this repository and also in clawpack/riemann pointing to versions that agree with what was used in producing the book.

change blob/master to blob/FA16 in pointers to GitHub repositories

---

README.md

The FA16 branch is the one for the published book and the README should point to files for this branch.
Also the binder link should start up a binder instance based on this branch.
I also updated the `gh-pages` branch (by pushing directly) so that the files
- http://www.clawpack.org/riemann_book/index.html
- http://www.clawpack.org/riemann_book/errata.html
better describe the branches, and the index now points to the `FA16` branch rather than `master`.

fix master links to point to FA16 in README.md

---

exact_solvers/euler_tammann.py
exact_solvers/nonlinear_elasticity.py
exact_solvers/shallow_water.py
exact_solvers/traffic_ramps.py

In recent versions of Python, using "is" to compare
with a string literal generates a warning.  This patch
avoids those warnings but does not change the behavior
of the code.

Use == for comparison with string literals.

---

exact_solvers/burgers_demos.py

This removes a visual bug, shown in the attachment.  In this visualization, short arrows go past where they should end.  And one arrow is plotted with length zero, which seems to result in a vertical line.  This PR just avoids plotting any arrows until there is enough space for them in the plot (second screenshot).

Avoid plotting too-short arrows
